### ISSUE TITLE
chat3.t turbo error

### ISSUE THREAD

**Issue by hoslo** [LuaLS/vscode-lua-webvue#13]
### Which OS are you using?

MacOS

### Expected Behaviour

reply normal

### Actual Behaviour

...

I also see the following error:

```
request to https://api.openai.com/v1/chat/completions failed, reason: write EPROTO 4809224376:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:594:SSL alert number 40
```

### Reproduction steps

1. ask

**Comment by carsakiller** [comment]
Hello. This is an interesting error. Can you provide more info about what you were doing when you received this error?

**Comment by carsakiller** [comment]
Closing stale and seemingly unrelated issue
