### ISSUE TITLE
LLS-Addons - Wrong repository url

### ISSUE THREAD

**Issue by TIMONz1535** [LuaLS/vscode-lua-webvue#19]
### How are you using the lua-language-server?

Visual Studio Code Extension (sumneko.lua)

### Which OS are you using?

Windows

### What is the issue affecting?

Plugins

### Expected Behaviour

![изображение](https://github.com/LuaLS/lua-language-server/assets/7351599/a1526804-0e0a-4532-945c-044b4bc02ac7)
redirects to an actual repository
https://github.com/LuaLS/LLS-Addons/tree/main/addons/garrysmod

### Actual Behaviour

If I press **View on GitHub** button I got link to **carsakiller**
https://github.com/carsakiller/LLS-Addons/tree/main/addons/garrysmod (last commit 6 months ago)
instead of **LuaLS** (sumneko)

### Reproduction steps

1. Go to 'Open Addon Managere'
2. Click 'View on GitHub'
3. See error 'carsakiller repo'

**Comment by carsakiller** [comment]
Thank you for the report!
